// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_BHCETA99zfVS3fSmWhse9sYENUkWnw',
    appId: '1:820757130873:web:adbac18fb79b3cf57e6ea8',
    messagingSenderId: '820757130873',
    projectId: 'seaotters-57347',
    authDomain: 'seaotters-57347.firebaseapp.com',
    storageBucket: 'seaotters-57347.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ISomEa41YbeAPp71Avdv9CSNnItLpVo',
    appId: '1:820757130873:android:2f946cf91c6c57d47e6ea8',
    messagingSenderId: '820757130873',
    projectId: 'seaotters-57347',
    storageBucket: 'seaotters-57347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5wlqyg9b7aI7Jl5K1qY4JzrSxPYFe7_g',
    appId: '1:820757130873:ios:724b06a6004907a47e6ea8',
    messagingSenderId: '820757130873',
    projectId: 'seaotters-57347',
    storageBucket: 'seaotters-57347.appspot.com',
    iosClientId: '820757130873-tgs66it2krepgvbaguu3i0i58b835efl.apps.googleusercontent.com',
    iosBundleId: 'com.Seaotter.StudyInsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5wlqyg9b7aI7Jl5K1qY4JzrSxPYFe7_g',
    appId: '1:820757130873:ios:724b06a6004907a47e6ea8',
    messagingSenderId: '820757130873',
    projectId: 'seaotters-57347',
    storageBucket: 'seaotters-57347.appspot.com',
    iosClientId: '820757130873-tgs66it2krepgvbaguu3i0i58b835efl.apps.googleusercontent.com',
    iosBundleId: 'com.Seaotter.StudyInsta',
  );
}
